### GET request
GET http://localhost:8080/api/games/word-guesser/hash

### GET request to generate new Sudoku instance
GET http://localhost:8080/api/sudoku/new?difficulty=HARD

### POST request to solve Sudoku puzzle
POST http://localhost:8080/api/sudoku/validate
Content-Type: application/json

{
  "id": "1b5a2a58-9eea-4e71-ad2e-69f84bc3da95",
  "grid": [
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780"
  ]
}
