### [Local] GET request to generate new Sudoku instance
GET http://localhost:8080/api/sudoku/new?difficulty=HARD

### [Local] POST request to solve Sudoku puzzle
POST http://localhost:8080/api/sudoku/validate
Content-Type: application/json

{
  "id": "1b5a2a58-9eea-4e71-ad2e-69f84bc3da95",
  "grid": [
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780",
    "123456780"
  ]
}

### [Deployed] GET request to generate new Sudoku instance
GET https://casual-game-generator.onrender.com/api/sudoku/new?difficulty=HARD

### [Deployed] POST request to solve Sudoku puzzle
POST https://casual-game-generator.onrender.com/api/sudoku/validate
Content-Type: application/json

{
  "id": "9f11db60-618c-4a2a-a972-165295d0a8bf",
  "grid": [
    "100260007",
    "280019530",
    "907008004",
    "356040070",
    "419003602",
    "800605041",
    "540020003",
    "093007100",
    "720036480"
  ]
}
